insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Afghanistan', 'AF', 'AFG', '004')
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Albania', 'AL', 'ALB','008');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Algeria', 'DZ', 'DZA','012');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'American Samoa', 'AS', 'ASM','016');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Andorra', 'AD', 'AND','020');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Angola', 'AO', 'AGO','024');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Anguilla', 'AI', 'AIA','660');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Antarctica', 'AQ', 'ATA','010');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Antigua and Barbuda', 'AG', 'ATG','028');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Argentina', 'AR', 'ARG','032');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Armenia', 'AM', 'ARM','051');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Aruba', 'AW', 'ABW','533');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Australia', 'AU', 'AUS','036');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Austria', 'AT', 'AUT','040');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Azerbaijan', 'AZ', 'AZE','031');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Bahamas (the)', 'BS', 'BHS','044');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Bahrain', 'BH', 'BHR','048');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Bangladesh', 'BD', 'BGD','050');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Barbados', 'BB', 'BRB','052');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Belarus', 'BY', 'BLR','112');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Belgium', 'BE', 'BEL','056');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Belize', 'BZ', 'BLZ','084');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Benin', 'BJ', 'BEN','204');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Bermuda', 'BM', 'BMU','060');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Bhutan', 'BT', 'BTN','064');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Bolivia (Plurinational State of)', 'BO', 'BOL','068');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES','535');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Bosnia and Herzegovina', 'BA', 'BIH','070');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Botswana', 'BW', 'BWA','072');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Bouvet Island', 'BV', 'BVT','074');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Brazil', 'BR', 'BRA','076');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'British Indian Ocean Territory (the)', 'IO', 'IOT','086');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Brunei Darussalam', 'BN', 'BRN','096');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Bulgaria', 'BG', 'BGR','100');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Burkina Faso', 'BF', 'BFA','854');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Burundi', 'BI', 'BDI','108');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Cabo Verde', 'CV', 'CPV','132');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Cambodia', 'KH', 'KHM','116');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Cameroon', 'CM', 'CMR','120');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Canada', 'CA', 'CAN','124');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Cayman Islands (the)', 'KY', 'CYM','136');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Central African Republic (the)', 'CF', 'CAF','140');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Chad', 'TD', 'TCD','148');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Chile', 'CL', 'CHL','152');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'China', 'CN', 'CHN','156');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Christmas Island', 'CX', 'CXR','162');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Cocos (Keeling) Islands (the)', 'CC', 'CCK','166');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Colombia', 'CO', 'COL','170');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Comoros (the)', 'KM', 'COM','174');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Congo (the Democratic Republic of the)', 'CD', 'COD','180');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Congo (the)', 'CG', 'COG','178');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Cook Islands (the)', 'CK', 'COK','184');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Costa Rica', 'CR', 'CRI','188');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Croatia', 'HR', 'HRV','191');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Cuba', 'CU', 'CUB','192');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Curaçao', 'CW', 'CUW','531');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Cyprus', 'CY', 'CYP','196');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Czechia', 'CZ', 'CZE','203');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Côte d''Ivoire', 'CI', 'CIV','384');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Denmark', 'DK', 'DNK','208');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Djibouti', 'DJ', 'DJI','262');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Dominica', 'DM', 'DMA','212');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Dominican Republic (the)', 'DO', 'DOM','214');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Ecuador', 'EC', 'ECU','218');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Egypt', 'EG', 'EGY','818');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'El Salvador', 'SV', 'SLV','222');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Equatorial Guinea', 'GQ', 'GNQ','226');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Eritrea', 'ER', 'ERI','232');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Estonia', 'EE', 'EST','233');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Eswatini', 'SZ', 'SWZ','748');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Ethiopia', 'ET', 'ETH','231');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Falkland Islands (the) [Malvinas]', 'FK', 'FLK','238');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Faroe Islands (the)', 'FO', 'FRO','234');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Fiji', 'FJ', 'FJI','242');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Finland', 'FI', 'FIN','246');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'France', 'FR', 'FRA','250');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'French Guiana', 'GF', 'GUF','254');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'French Polynesia', 'PF', 'PYF','258');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'French Southern Territories (the)', 'TF', 'ATF','260');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Gabon', 'GA', 'GAB','266');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Gambia (the)', 'GM', 'GMB','270');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Georgia', 'GE', 'GEO','268');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Germany', 'DE', 'DEU','276');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Ghana', 'GH', 'GHA','288');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Gibraltar', 'GI', 'GIB','292');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Greece', 'GR', 'GRC','300');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Greenland', 'GL', 'GRL','304');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Grenada', 'GD', 'GRD','308');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Guadeloupe', 'GP', 'GLP','312');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Guam', 'GU', 'GUM','316');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Guatemala', 'GT', 'GTM','320');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Guernsey', 'GG', 'GGY','831');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Guinea', 'GN', 'GIN','324');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Guinea-Bissau', 'GW', 'GNB','624');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Guyana', 'GY', 'GUY','328');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Haiti', 'HT', 'HTI','332');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Heard Island and McDonald Islands', 'HM', 'HMD','334');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Holy See (the)', 'VA', 'VAT','336');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Honduras', 'HN', 'HND','340');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Hong Kong', 'HK', 'HKG','344');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Hungary', 'HU', 'HUN','348');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Iceland', 'IS', 'ISL','352');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'India', 'IN', 'IND','356');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Indonesia', 'ID', 'IDN','360');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Iran (Islamic Republic of)', 'IR', 'IRN','364');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Iraq', 'IQ', 'IRQ','368');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Ireland', 'IE', 'IRL','372');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Isle of Man', 'IM', 'IMN','833');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Israel', 'IL', 'ISR','376');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Italy', 'IT', 'ITA','380');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Jamaica', 'JM', 'JAM','388');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Japan', 'JP', 'JPN','392');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Jersey', 'JE', 'JEY','832');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Jordan', 'JO', 'JOR','400');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Kazakhstan', 'KZ', 'KAZ','398');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Kenya', 'KE', 'KEN','404');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Kiribati', 'KI', 'KIR','296');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Korea (the Democratic People''s Republic of)', 'KP', 'PRK','408');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Korea (the Republic of)', 'KR', 'KOR','410');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Kuwait', 'KW', 'KWT','414');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Kyrgyzstan', 'KG', 'KGZ','417');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Lao People''s Democratic Republic (the)', 'LA', 'LAO','418');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Latvia', 'LV', 'LVA','428');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Lebanon', 'LB', 'LBN','422');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Lesotho', 'LS', 'LSO','426');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Liberia', 'LR', 'LBR','430');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Libya', 'LY', 'LBY','434');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Liechtenstein', 'LI', 'LIE','438');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Lithuania', 'LT', 'LTU','440');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Luxembourg', 'LU', 'LUX','442');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Macao', 'MO', 'MAC','446');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Madagascar', 'MG', 'MDG','450');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Malawi', 'MW', 'MWI','454');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Malaysia', 'MY', 'MYS','458');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Maldives', 'MV', 'MDV','462');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Mali', 'ML', 'MLI','466');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Malta', 'MT', 'MLT','470');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Marshall Islands (the)', 'MH', 'MHL','584');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Martinique', 'MQ', 'MTQ','474');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Mauritania', 'MR', 'MRT','478');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Mauritius', 'MU', 'MUS','480');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Mayotte', 'YT', 'MYT','175');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Mexico', 'MX', 'MEX','484');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Micronesia (Federated States of)', 'FM', 'FSM','583');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Moldova (the Republic of)', 'MD', 'MDA','498');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Monaco', 'MC', 'MCO','492');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Mongolia', 'MN', 'MNG','496');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Montenegro', 'ME', 'MNE','499');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Montserrat', 'MS', 'MSR','500');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Morocco', 'MA', 'MAR','504');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Mozambique', 'MZ', 'MOZ','508');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Myanmar', 'MM', 'MMR','104');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Namibia', 'NA', 'NAM','516');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Nauru', 'NR', 'NRU','520');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Nepal', 'NP', 'NPL','524');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Netherlands (the)', 'NL', 'NLD','528');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'New Caledonia', 'NC', 'NCL','540');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'New Zealand', 'NZ', 'NZL','554');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Nicaragua', 'NI', 'NIC','558');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Niger (the)', 'NE', 'NER','562');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Nigeria', 'NG', 'NGA','566');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Niue', 'NU', 'NIU','570');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Norfolk Island', 'NF', 'NFK','574');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Northern Mariana Islands (the)', 'MP', 'MNP','580');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Norway', 'NO', 'NOR','578');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Oman', 'OM', 'OMN','512');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Pakistan', 'PK', 'PAK','586');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Palau', 'PW', 'PLW','585');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Palestine, State of', 'PS', 'PSE','275');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Panama', 'PA', 'PAN','591');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Papua New Guinea', 'PG', 'PNG','598');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Paraguay', 'PY', 'PRY','600');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Peru', 'PE', 'PER','604');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Philippines (the)', 'PH', 'PHL','608');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Pitcairn', 'PN', 'PCN','612');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Poland', 'PL', 'POL','616');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Portugal', 'PT', 'PRT','620');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Puerto Rico', 'PR', 'PRI','630');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Qatar', 'QA', 'QAT','634');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Republic of North Macedonia', 'MK', 'MKD','807');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Romania', 'RO', 'ROU','642');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Russian Federation (the)', 'RU', 'RUS','643');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Rwanda', 'RW', 'RWA','646');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Réunion', 'RE', 'REU','638');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Saint Barthélemy', 'BL', 'BLM','652');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN','654');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Saint Kitts and Nevis', 'KN', 'KNA','659');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Saint Lucia', 'LC', 'LCA','662');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Saint Martin (French part)', 'MF', 'MAF','663');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Saint Pierre and Miquelon', 'PM', 'SPM','666');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Saint Vincent and the Grenadines', 'VC', 'VCT','670');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Samoa', 'WS', 'WSM','882');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'San Marino', 'SM', 'SMR','674');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Sao Tome and Principe', 'ST', 'STP','678');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Saudi Arabia', 'SA', 'SAU','682');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Senegal', 'SN', 'SEN','686');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Serbia', 'RS', 'SRB','688');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Seychelles', 'SC', 'SYC','690');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Sierra Leone', 'SL', 'SLE','694');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Singapore', 'SG', 'SGP','702');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Sint Maarten (Dutch part)', 'SX', 'SXM','534');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Slovakia', 'SK', 'SVK','703');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Slovenia', 'SI', 'SVN','705');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Solomon Islands', 'SB', 'SLB','090');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Somalia', 'SO', 'SOM','706');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'South Africa', 'ZA', 'ZAF','710');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'South Georgia and the South Sandwich Islands', 'GS', 'SGS','239');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'South Sudan', 'SS', 'SSD','728');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Spain', 'ES', 'ESP','724');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Sri Lanka', 'LK', 'LKA','144');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Sudan (the)', 'SD', 'SDN','729');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Suriname', 'SR', 'SUR','740');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Svalbard and Jan Mayen', 'SJ', 'SJM','744');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Sweden', 'SE', 'SWE','752');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Switzerland', 'CH', 'CHE','756');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Syrian Arab Republic', 'SY', 'SYR','760');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Taiwan (Province of China)', 'TW', 'TWN','158');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Tajikistan', 'TJ', 'TJK','762');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Tanzania, United Republic of', 'TZ', 'TZA','834');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Thailand', 'TH', 'THA','764');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Timor-Leste', 'TL', 'TLS','626');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Togo', 'TG', 'TGO','768');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Tokelau', 'TK', 'TKL','772');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Tonga', 'TO', 'TON','776');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Trinidad and Tobago', 'TT', 'TTO','780');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Tunisia', 'TN', 'TUN','788');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Turkey', 'TR', 'TUR','792');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Turkmenistan', 'TM', 'TKM','795');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Turks and Caicos Islands (the)', 'TC', 'TCA','796');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Tuvalu', 'TV', 'TUV','798');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Uganda', 'UG', 'UGA','800');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Ukraine', 'UA', 'UKR','804');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'United Arab Emirates (the)', 'AE', 'ARE','784');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'United Kingdom of Great Britain and Northern Ireland (the)', 'GB', 'GBR','826');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'United States Minor Outlying Islands (the)', 'UM', 'UMI','581');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'United States of America (the)', 'US', 'USA','840');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Uruguay', 'UY', 'URY','858');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Uzbekistan', 'UZ', 'UZB','860');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Vanuatu', 'VU', 'VUT','548');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Venezuela (Bolivarian Republic of)', 'VE', 'VEN','862');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Viet Nam', 'VN', 'VNM','704');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Virgin Islands (British)', 'VG', 'VGB','092');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Virgin Islands (U.S.)', 'VI', 'VIR','850');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Wallis and Futuna', 'WF', 'WLF','876');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Western Sahara', 'EH', 'ESH','732');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Yemen', 'YE', 'YEM','887');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Zambia', 'ZM', 'ZMB','894');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Zimbabwe', 'ZW', 'ZWE','716');
insert into countries( created_at, country_name, country_code_a2, country_code_a3, country_code_numeric) values( current_timestamp, 'Åland Islands', 'AX', 'ALA','248');
